spring.application.name=demo

# Cookie configuration in production set to true!
application.security.cookie.secure=false

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=demo_user
spring.datasource.password=demo_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable Problem Details for Spring MVC
spring.mvc.problemdetails.enabled=true

# JWT Configuration
application.security.jwt.secret-key=8HlFRY203XUsyzaZivQLpGaP2V/Dt66keCpxvgQfywUi6G/t17FDa2J+Hflwe+lEEihLgQSXcDfQKWh/dTNOyw==
# 15 minutes = 900000 ms
application.security.jwt.expiration.access-token=900000
# 30 days = 2592000000 ms
application.security.jwt.expiration.refresh-token=2592000000